# Generated by Django 4.2.5 on 2023-09-19 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backapp", "0002_alter_order_paymentresult"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="orderItems",),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="backapp.order",
            ),
        ),
    ]
