# Generated by Django 4.2.5 on 2023-09-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backapp", "0003_remove_order_orderitems_orderitem_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem", old_name="qty", new_name="quantity",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="countInStock",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="slug",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
