# Generated by Django 4.2.5 on 2023-09-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backapp", "0005_alter_order_paidat"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
