import { User } from "./models/userModel";
import { Product } from "./models/productModel";
import bcrypt from "bcryptjs";

export const sampleProduct: Product[] = [
  {
    name: "Nike slim shirt",
    slug: "nike-slim-shirt",
    category: "Shirts",
    image: "../images/p1.jpg",
    price: 120,
    countInStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    description: "high quality product",
  },
  {
    name: "Adidas fit shirt",
    slug: "adidas-fit-shirt",
    category: "Shirts",
    image: "../images/p2.jpg",
    price: 250,
    countInStock: 20,
    brand: "Adidas",
    rating: 4.0,
    numReviews: 10,
    description: "high quality product",
  },
  {
    name: "Nike slim pants",
    slug: "nike-slim-pants",
    category: "Pants",
    image: "../images/p3.jpg",
    price: 120,
    countInStock: 15,
    brand: "Nike",
    rating: 4.5,
    numReviews: 14,
    description: "high quality product",
  },
  {
    name: "Adidas fit pants",
    slug: "adidas-fit-pants",
    category: "Pants",
    image: "../images/p4.jpg",
    price: 90,
    countInStock: 5,
    brand: "Adidas",
    rating: 4.5,
    numReviews: 10,
    description: "high quality product",
  },
  {
    name: "puma fit pants",
    slug: "puma-fit-shirt",
    category: "Shirts",
    image: "../images/p5.jpg",
    price: 50,
    countInStock: 0,
    brand: "puma",
    rating: 4.5,
    numReviews: 10,
    description: "high quality product",
  },
  {
    name: "lv fit shirt",
    slug: "lv-fit-shirt",
    category: "Shirts",
    image: "../images/p5.jpg",
    price: 500,
    countInStock: 1,
    brand: "lv",
    rating: 4.8,
    numReviews: 1,
    description: "high quality product",
  },
  {
    name: "p fit shirt",
    slug: "p-fit-shirt",
    category: "Shirts",
    image: "../images/p1.jpg",
    price: 300,
    countInStock: 1,
    brand: "p",
    rating: 4.8,
    numReviews: 1,
    description: "high quality product",
  },
];

export const sampleUsers: User[] = [
  {
    name: "Joe",
    email: "admin@example.com",
    password: bcrypt.hashSync("123456"),
    isAdmin: true,
  },
  {
    name: "Jane",
    email: "user1@example.com",
    password: bcrypt.hashSync("123456"),
    isAdmin: false,
  },
  {
    name: "Jane",
    email: "user2@example.com",
    password: bcrypt.hashSync("123456"),
    isAdmin: false,
  },
];
